name: 'Docker Releaser for ECR'
description: 'Create git tag and GitHub release for Docker image'
author: 'NSXBet'

inputs:
  image:
    description: 'Image name (e.g., "argus-api")'
    required: true
  ecr-registry:
    description: 'ECR registry URL'
    required: false
    default: '492684252576.dkr.ecr.us-east-1.amazonaws.com'
  gh-token:
    description: 'GitHub token for releases'
    required: true

runs:
  using: composite
  steps:
    - name: Read VERSION
      id: version
      shell: bash
      run: |
        VERSION=$(cat VERSION | tr -d '\n')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create git tag
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.version }}
        IMAGE: ${{ inputs.image }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        TAG="${IMAGE}-v${VERSION}"
        git tag -f "$TAG" -m "Release $IMAGE $VERSION"
        git push -f origin "$TAG"

    - name: Create GitHub release
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.version }}
        IMAGE: ${{ inputs.image }}
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        TAG="${IMAGE}-v${VERSION}"

        gh release delete "$TAG" --yes 2>/dev/null || true
        gh release create "$TAG" \
          --title "$IMAGE $VERSION" \
          --notes "Docker image: \`${ECR_REGISTRY}/${IMAGE}:${VERSION}\`

        Platforms: linux/amd64, linux/arm64"

branding:
  icon: 'package'
  color: 'blue'
